# Travis CI configuration file

language: c

script: gcc src/CCalc.c -o ./CCalc.o && gcc src/Test_CCalc.c -o ./Test_CCalc.o

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
